spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: Welcome@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

camel:
  springboot:
    name: userservice-camel