name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Recommended distribution for OpenJDK
        cache: 'maven' # Caches Maven dependencies for faster builds

    - name: Build with Maven
      run: mvn -B package --file pom.xml # Builds the project and packages it into a JAR/WAR

    - name: Run Java application (if applicable)
      run: java -jar target/your-application.jar # Replace 'your-application.jar' with your actual JAR file name
