name: CI - Build, Test, Sonar, Security

on:
  push:
    branches:
      - "main"
      - "develop"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "release/*"

jobs:
  build-test-sonar:
    name: Build, Test & Sonar Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & Test with Maven
        run: mvn -B clean verify

      - name: Run SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  #f608dfab484302c1943ebe0211713a5cce3a040d
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

  
